import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

type HealthState = { llmAvailable: boolean; mode: "mock" | "live"; model?: string };

const FALLBACK: HealthState = { llmAvailable: false, mode: "mock" };

export function AiModeBadge() {
  const [health, setHealth] = useState<HealthState>(FALLBACK);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/health")
      .then((r) => (r.ok ? r.json() : FALLBACK))
      .then((data) => {
        if (!cancelled) setHealth({ ...FALLBACK, ...data });
      })
      .catch(() => {
        if (!cancelled) setHealth(FALLBACK);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const isLive = health.mode === "live" && health.llmAvailable;
  return (
    <Popover>
      <PopoverTrigger asChild>
        <button className="focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary rounded-full">
          <Badge variant={isLive ? "ai" : "muted"} className="cursor-pointer">
            <Sparkles className="h-3 w-3" />
            {isLive ? "Live AI" : "Mock AI"}
          </Badge>
        </button>
      </PopoverTrigger>
      <PopoverContent align="end" className="text-sm">
        {isLive ? (
          <>
            <p className="font-semibold mb-1 text-foreground">Live AI mode</p>
            <p className="text-muted-foreground">
              Recommendations and insights are generated by Claude ({health.model ?? "default model"}).
            </p>
          </>
        ) : (
          <>
            <p className="font-semibold mb-1 text-foreground">Mock AI mode</p>
            <p className="text-muted-foreground">
              The app is running with rule-based logic only — no live LLM calls. Set{" "}
              <code className="px-1 rounded bg-background text-xs">LLM_MODE=live</code> and
              provide <code className="px-1 rounded bg-background text-xs">ANTHROPIC_API_KEY</code>{" "}
              to enable AI-generated recommendations.
            </p>
          </>
        )}
      </PopoverContent>
    </Popover>
  );
}
